name: Docker Image CI com Relatório Automático

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    env:
      TZ: 'America/Sao_Paulo'
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Passo 2: Faz o build da imagem Docker e armazena o status
      - name: Build the Docker image
        id: docker_build
        run: docker build . --file Dockerfile --tag marieli-docker:latest

      # Passo 3: Cria o conteúdo do relatório em HTML
      - name: Generate HTML Report Content
        id: report_content
        run: |
          BUILD_STATUS="${{ steps.docker_build.outcome }}"
          STATUS_CLASS=$(if [ "$BUILD_STATUS" = "success" ]; then echo "sucesso"; else echo "erro"; fi)
          WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          LOG_CONTENT=$(docker build . --file Dockerfile --tag marieli-docker:latest 2>&1)
          
          # Conteúdo HTML gerado
          REPORT_HTML=$(cat <<EOF
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <title>Relatório do Build Automático – GitHub Actions</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
    body {font-family: Arial, sans-serif; background: #f7faff; color: #222; margin:0; padding:40px;}
    .relatorio {background: #fff; border-radius: 14px; box-shadow: 0 2px 16px rgba(208, 228, 251, 0.25); max-width: 650px; margin: 0 auto; padding: 32px;}
    h2 {color: #0b57d0;}
    h3 {color: #3762bc;}
    pre {background: #ecf4fb; color: #153530; padding: 14px 12px; border-radius: 7px; overflow-x:auto; white-space: pre-wrap; word-wrap: break-word;}
    .status {font-size:1.09em;}
    .tentativas {margin-top:18px;}
    .erro {color: #b52e23;}
    .sucesso {color: #218c4b;}
  </style>
</head>
<body>
  <div class="relatorio">
    <h2>Relatório do Build Automático (GitHub Actions)</h2>
    <p class="status"><b>Status:</b> <span class="${STATUS_CLASS}">${BUILD_STATUS}</span></p>
    <p><b>Data/Hora:</b> $(date +"%Y-%m-%d %H:%M:%S %Z")</p>
    <p><b>Link da Execução:</b> <a href="${WORKFLOW_URL}">Ver no GitHub Actions</a></p>
    
    <h3>Log Principal:</h3>
    <pre>
${LOG_CONTENT}
    </pre>
    
    <h3>Histórico/Tentativas:</h3>
    <p>Como o relatório é gerado automaticamente a cada push, o histórico de tentativas pode ser acessado no link acima, na aba "Actions".</p>
    
  </div>
</body>
</html>
EOF
          )
          echo "$REPORT_HTML" > relatorio-actions.html # Cria o arquivo HTML

      # Passo 4: Comita o relatório atualizado
      - name: Commit Report
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualiza relatorio-actions.html"
          branch: main
          file_pattern: 'relatorio-actions.html'
