name: Docker Image CI com Relatório Automático

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      TZ: 'America/Sao_Paulo'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build the Docker image
        id: docker_build
        run: docker build . --file Dockerfile --tag marieli-docker:latest

      - name: Generate HTML Report
        run: |
          BUILD_STATUS="${{ steps.docker_build.outcome }}"
          WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo '<!DOCTYPE html>
          <html lang="pt-BR">
          <head>
            <meta charset="UTF-8">
            <title>Relatório de Build da Imagem Docker</title>
            <style>
              body { font-family: Arial, sans-serif; background: #111; color: #fff; padding: 20px; }
              h1 { color: #00ffcc; }
              pre { background: #222; padding: 10px; border-radius: 5px; color: #0f0; }
              a { color: #00ccff; }
              details { background: #1a1a1a; padding: 10px; border-radius: 5px; }
            </style>
          </head>
          <body>
            <h1>Relatório de Build da Imagem Docker</h1>
            <p><b>Status do Build:</b> '"$BUILD_STATUS"'</p>
            <p><b>Data e Hora:</b> '"$(date +"%Y-%m-%d %H:%M:%S %Z")"'</p>
            <p><b>Link da Execução:</b> <a href="'"$WORKFLOW_URL"'" target="_blank">Ver no GitHub Actions</a></p>
            <hr>
            <h2>Logs da Execução</h2>
            <details>
              <summary>Clique para expandir os logs</summary>
              <pre>'"$(docker build . --file Dockerfile --tag marieli-docker:latest 2>&1)"'</pre>
            </details>
          </body>
          </html>' > RELATORIO.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
